const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'src', 'components', 'TurneroView.tsx');
const content = fs.readFileSync(filePath, 'utf8');
const lines = content.split('\n');
console.log('Before:', lines.length, 'lines');
const trimmed = lines.slice(0, 222).join('\n') + '\n';
fs.writeFileSync(filePath, trimmed, 'utf8');
const verify = fs.readFileSync(filePath, 'utf8').split('\n').length;
console.log('After:', verify, 'lines');
process.exit(0);
